# Generated by Django 4.1.2 on 2022-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='slug',
            field=models.SlugField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
