# Generated by Django 4.1.2 on 2022-10-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='number_rating',
            field=models.IntegerField(default=0, verbose_name='Количество оценок'),
        ),
    ]
