# Generated by Django 4.1.2 on 2022-11-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_poem_author_alter_poem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='time_update',
        ),
    ]
