# Generated by Django 4.1.2 on 2022-10-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_poem_tittle_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='tittle',
            new_name='title',
        ),
    ]
