# Generated by Django 4.1.2 on 2022-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_remove_poem_time_create_remove_poem_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
