# Generated by Django 4.1.2 on 2022-10-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_rename_tittle_poem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Отзыв'),
        ),
    ]
